[general]
pidfile="burrow.pid"
stdout-logfile="burrow.out"
access-control-allow-origin="mysite.example.com"

[logging]
filename="logs/burrow.log"
level="info"
maxsize=100
maxbackups=30
maxage=10
use-localtime=false
use-compression=true

[zookeeper]
servers=[ "10.10.3.110:2181", "10.10.3.237:2181", "10.10.3.19:2181" ]
timeout=6
root-path="/burrow"

[client-profile.test]
client-id="burrow-test"
kafka-version="0.10.0.1"

[cluster.test]
class-name="kafka"
servers=[ "10.10.3.110:9092", "10.10.3.237:9092", "10.10.3.19:9092" ]
client-profile="test"
topic-refresh=120
offset-refresh=30

[consumer.test]
class-name="kafka"
cluster="test"
servers=[ "10.10.3.110:9092", "10.10.3.237:9092", "10.10.3.19:9092" ]
client-profile="test"
group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
group-whitelist=""

[consumer.test_zk]
class-name="kafka_zk"
cluster="test"
servers=[ "10.10.3.110:2181", "10.10.3.237:2181", "10.10.3.19:2181" ]
zookeeper-path=""
zookeeper-timeout=30
group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
group-whitelist=""

[httpserver.default]
address=":9001"

[storage.default]
class-name="inmemory"
workers=20
intervals=15
expire-group=604800
min-distance=1
